In [20]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [21]:
import numpy as np

In [22]:
a=np.array([1,2,3])

In [23]:
print(a)

[1 2 3]


In [24]:
c=np.array([(4,5,6),(1,2,3)])

In [25]:
print(c)

[[4 5 6]
 [1 2 3]]


In [26]:
trans=np.transpose(c)